image:
- Visual Studio 2017

platform:
  - x64

before_build:
  - echo "Downloading conan..."
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user # Create the conan data directory
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan --version

build_script:
  - mkdir build
  - cd build
  - conan install .. -s build_type=Release -s compiler="Visual Studio" --build=missing
  - cmake .. -G "Visual Studio 15 2017 Win64"
  - cmake --build . --config Release
